version: '3'

# #####################
# VOLUMES
# #####################

volumes:
  jwt_tokens:
    driver: local
  rabbitdata:
    driver: local
  sqldata:
    driver: local
  graphdata:
    driver: local
  mongodata:
    driver: local
  pureftpd:
    driver: local
  # redisdata:
  #   driver: local

# #####################
# NETWORKS
# #####################

networks:
  # default:
  i_net:
  app_net:
  proxy_net:
  db_net:
    # driver: bridge
    ipam:
      driver: default
      config:
        # Note: use this configuration to match inside internal rules
        # TOFIX: make this an env variable
        - subnet: ${DB_SUBNET}/16

# #####################
# SERVICES
# #####################
services:

  ##############################
  # MAIN CONTAINER
  backend:
    # command: sleep infinity
    build: ../builds_base/backend
    image: ${COMPOSE_PROJECT_NAME}/backend:template
    hostname: restapi
    # user: root
    # working_dir: /code
    environment:
      # TODO: active or not
      ACTIVATE: 0
      FLASK_APP: run.py
      VANILLA_PACKAGE: custom
      JWT_APP_SECRETS: ${JWT_APP_SECRETS}
    volumes:
      # Base code
      - ../backend:/code
      # Vanilla code
      - ..:/code/${COMPOSE_PROJECT_NAME}
      # JWT tokens secret
      - jwt_tokens:${JWT_APP_SECRETS}
      # Tests
      - ../tests/backend:/code/test/custom
    networks:
      app_net:
        aliases:
          - ${FLASK_HOST}
      db_net:
      # i_net:

  ##############################
  rabbit:
    image: rabbitmq:latest
    hostname: rabbit
    volumes:
      - rabbitdata:/var/lib/rabbitmq
    environment:
      ACTIVATE: 0

  celery:
    build: ../builds_base/celery
    image: ${COMPOSE_PROJECT_NAME}/celery:template
    # hostname: celworker
    # command: celery worker -c 1 -A flask_ext.flask_celery.worker.celery_app
    user: root
    working_dir: /code
    environment:
      ACTIVATE: 0
      VANILLA_PACKAGE: custom
      JWT_APP_SECRETS: ${JWT_APP_SECRETS}
    volumes:
      # Base code
      - ../backend:/code
      # JWT tokens secret
      - jwt_tokens:/jwt_tokens

  ##############################
  # The proxy which decides to redirect requests
  # based on URLs received.
  # Redirects /api to backend
  # Listens on port 80
  # Should implements SSL on 443

  proxy:
    # image: nginx:1.11-alpine
    build: ../builds_base/proxy
    image: ${COMPOSE_PROJECT_NAME}/proxy:template
    # image: nginx:rapydo
    hostname: reverseproxy
    networks:
      proxy_net:
        aliases:
          - ${PROXY_HOST}
      app_net:
    # volumes:
    #   # - ../containers/nginx_proxy:/etc/nginx/conf.d
    #   - ../confs/nginx/production.conf:/etc/nginx/sites-enabled/production
    depends_on:
      # NOTE: you have to rewrite all depends_on in a new yml file
      # at the moment they do not cumulate
      - backend
    environment:
      ACTIVATE: 0

  #############
  # Client interface if using swagger
  swaggerui:
    build: ../builds_base/swaggerui
    image: ${COMPOSE_PROJECT_NAME}/swaggerui:template
    # image: swagger-ui:rapydo
    environment:
      ACTIVATE: 0

  ######################
  postgres:
    image: postgres:9.6
    volumes:
      - sqldata:/var/lib/postgresql/data
      - ../builds_base/postgres/pgs_init.sh:/docker-entrypoint-initdb.d/setup-my-schema.sh:ro
    environment:
      ACTIVATE: 0
      POSTGRES_USER: "${PLACEHOLDER}"
      POSTGRES_PASSWORD: "${PLACEHOLDER}"
      POSTGRES_DBS: ${PLACEHOLDER}
    networks:
      db_net:
        aliases:
          - ${ALCHEMY_HOST}

  #################################
  neo4j:
    image: neo4j:3.2.0
    volumes:
      - graphdata:/data
    networks:
      db_net:
        aliases:
          - ${GRAPHDB_HOST}
    environment:
      ACTIVATE: 0
      NEO4J_AUTH: neo4j/${PLACEHOLDER}
      # NEO4J_dbms_memory_pagecache_size: 2048M
      # NEO4J_dbms_memory_heap_maxSize: 4096M
    # ports:
    #   - 9090:7474
    #   - 7687:7687

  #################################
  # Mongo DB
  mongodb:
    image: mongo:3.4
    volumes:
      - mongodata:/data/db
    networks:
      db_net:
        aliases:
          - ${MONGO_HOST}
    environment:
      ACTIVATE: 0

  #################################
  # FTP
  ftp:
    # image: stilliard/pure-ftpd:latest
    build: ../builds_base/ftp
    image: ${COMPOSE_PROJECT_NAME}/ftp:template
    volumes:
      - pureftpd:/etc/pure-ftpd/passwd
  # /etc/ssl/private/ A directory containing a single pure-ftpd.pem file
  # with the server's SSL certificates for TLS support. Optional TLS is
  # automatically enabled when the container finds this file on startup.
    environment:
      ACTIVATE: 0
      PUBLICHOST: ${PROJECT_DOMAIN}
      ADDED_FLAGS: -d -d

  #############
  # iRODS iCAT server (usually for EUDAT B2safe)
  icat:
    # B2safe instance on irods
    build: ../builds_base/icat
    image: ${COMPOSE_PROJECT_NAME}/icat:template
    # image: b2safe:rapydo
    hostname: ${IRODS_HOST}
    # command: sleep infinity
    environment:
      ACTIVATE: 0
      POSTGRES_HOST: ${PLACEHOLDER}
      POSTGRES_USER: ${PLACEHOLDER}
      POSTGRES_PASSWORD: ${PLACEHOLDER}
      IRODS_HOST: ${PLACEHOLDER}
      IRODS_PORT: ${PLACEHOLDER}
      IRODS_ZONE: ${PLACEHOLDER}
      IRODS_DB: ${PLACEHOLDER}
      IRODS_USER: ${PLACEHOLDER}
      IRODS_PASSWORD: ${PLACEHOLDER}
    networks:
      i_net:
        aliases:
          - ${IRODS_HOST}
      db_net:
    depends_on:
      - postgres

  # #################################
  # ADMINISTRATIONS
  # #################################

  #################################
  # Database administration

  # This docker image let you access sqllite/postgres/mysql
  # with a phpmyadmin-like web page
  sqladmin:
    environment:
      ACTIVATE: 0
    # image: sqladminer:rapydo
    build: ../builds_base/sqladmin
    image: ${COMPOSE_PROJECT_NAME}/sqladmin:template
    # image: eudatb2stage/sqladminer:latest
    networks:
      db_net:

  #############
  # REST API client (wget, curl, httpie, http-prompt)
  restclient:
    build: ../builds_base/restclient
    image: ${COMPOSE_PROJECT_NAME}/restclient:template
    # image: apiclient:rapydo
    environment:
      ACTIVATE: 0
      MAIN_ENDPOINT: ${API_MAIN_ENDPOINT}
    volumes:
      # TOFIX
      - ../backend:/code/core
      - ..:/code/custom

  # #################################
  # OTHERS
  # #################################

  #######################
  # elasticsearch:
  #   image: elasticsearch
  #   hostname: elastic
  #   volumes:
  #       - restangulask_graphbased_elasticdata:/usr/share/elasticsearch/data

  #################################
  # SMTP server
  # smtp:
  #   image: namshi/smtp
  #   environment:
  #     # GMAIL_USER: -
  #     # GMAIL_PASSWORD: -
  #     - SMARTHOST_ADDRESS=mail.cineca.it
  #     - SMARTHOST_PORT=587
  #     - SMARTHOST_USER=m.dantonio
  #     - SMARTHOST_PASSWORD=-
  #     - SMARTHOST_ALIASES=*.cineca.it

  #################################
  # REDIS key/value store
  # redisqueue:
  #   image: redis:alpine
  #   command: redis-server --appendonly yes
  #   hostname: myqueue
  #   volumes:
  #     - redisdata:/data
